### ISSUE TITLE
06 -- More Responsive -- Garrett Lee Graham Anderson

### ISSUE THREAD

**Issue by GarrettGraham** [TheIronYard--Orlando/FEE--2015--SPRING#86]
* [x] **Yak Shaving** (L)
  * [x] Create a new _WIP Issue_ named `06 -- More Responsive -- YOUR NAME`with tasks and estimates
  * [x] Ensure your _old_ feature branch is merged and in `master` on Cloud 9
  * [x] Create a new branch on Cloud 9 called `feature/06--more-responsive`
  * [ ] Take screenshots of the _medium_ and _small_ breakpoints, add them to Cloud 9, and push them to Github
  * [x] _Immediately_ open a PR!
* [ ] **Vertical Timeline -- Medium Size** (L)
  * [ ] Checkpoint: Skitched it up!
  * [ ] Checkpoint: First medium-size media query!
  * [ ] Checkpoint: Well, I applied some styles...
  * [ ] Checkpoint: Nailed it.
* [ ] **Vertical Timeline -- Small Size** (L)
  * [ ] Checkpoint: Skitched that bad mamma-jamma!
  * [ ] Checkpoint: First small-size media query!
  * [ ] Checkpoint: Yo, dawg, I heard you liked CSS...
  * [ ] Checkpoint: Mission complete! :checkered_flag:

**Comment by GarrettGraham** [comment]
Having a really tough time working with time and not allowing myself to get overwhelmed and stressed. Already dealing with sleep deprivation whcih is why i needed to leave early yesterday. i dont like the local option because i am still unsure how work it with ease.

**Comment by LoganArnett** [comment]
Don't be discourage Garrett this is all completely new to you, I was in the exact same place a few months ago, especially with Git. The local option will definitely become the easiest path for you once you become comfortable with it as it typically carries less headaches than c9.

**Comment by al-the-x** [comment]
You're getting there! Keep breaking larger tasks down into smaller tasks, and time-box the smaller tasks so that you don't get stuck on rabbit trails. Set a timer for yourself, and be strict about it. You're not the only one struggling with time management or remembering to come up for air. Everyone's brains are packed with dozens of unrelated-but-similar concepts at the moment; it's a train wreck in there. It'll sort itself out as you Keep Calm and Carry On.

**Comment by al-the-x** [comment]
Note how your PR showed up as a link on this issue simply because you put a link to this issue in your PR. It's the little bookmark on the comment timeline that reads:

> GarretGraham referenced this issue in GarretGraham/TIY-Assignments X days ago

And it also gives me the status of your PR: **Merged**. You've just unlocked a shortcut for your workflow. As long as you add a link to your _WIP Issue_ as a comment on your _PR_, you get a link to your _PR_ for free... :eyeglasses:

**Comment by GarrettGraham** [comment]
Thank you very much for the words of encouragement. I'm feeling a lot more comfortable being uncomfortable and I will surely take more advantage of my peers.

Garrett
